gantt
    Title Swim Meets
    dateFormat YYY-MM-DD
    todayMarker stroke-width:5px,stroke:#0f0,opacity:0.5

    Section NGSL

    NORTH SPLASH MEET (May 27 deadline, at Ruby C Fulbright, Clarkesville) :active, 2025-06-07, 3d
    Saturday NGSL Invitational (at Ruby C Fulbright, Clarkesville) :active, 2025-06-21, 3d
    NGSL League Champs :crit, 2025-07-28, 2d

    Section GRPA

    Qualifier! GRPA DISTRICT Meet (at Gainesville, Deadline June 16) :active, 2025-06-27, 2d
    GRPA A State - SCY (Columbus)  :crit, 2025-07-25, 2d

    Section Fun meets - free
    Saturday Meet (at Ruby C Fulbright, Clarkesville) :meet1,2025-05-24, 1d
    Carol Tate LC Meet (Emoty Univ, Atlanta) :active, 2025-05-31, 2d
    Dual Free (at Reunion) :q_ngsl, 2025-06-05, 1d
    SST Savannah LC Meet (Savannah) :meet1,2025-06-13, 2d
    Dual FREE Meet (Dahlonega)  :meet1,2025-06-19, 2d
